# .github/workflows/build-macos.yml
name: Build macOS App (Bundled FFmpeg)

on:
  push:
    branches: [ main ] # Jalan saat push ke main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Libraries
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter requests yt-dlp pyinstaller

    - name: Download FFmpeg for macOS
      run: |
        curl -L https://evermeet.cx/ffmpeg/getrelease/ffmpeg/zip -o ffmpeg.zip
        unzip -o ffmpeg.zip
        if [ -f ffmpeg ]; then chmod +x ffmpeg; fi

    - name: Build App with PyInstaller
      run: |
        pyinstaller --windowed --onefile --noconfirm \
          --name "AutoClipIntisari_Mac" \
          --add-binary "ffmpeg:." \
          AutoClipintisari.py

    - name: List build output
      run: |
        ls -lah dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Intisari-Clipper-MacOS
        path: dist/*
        retention-days: 7
