# .github/workflows/build-windows.yml
name: Build Windows App

on:
  push:
    branches: [ main ] # Jalan setiap ada update code

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter requests yt-dlp pyinstaller

    - name: Download FFmpeg for Windows
      run: |
        Invoke-WebRequest -Uri "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip" -OutFile "ffmpeg.zip"
        Expand-Archive ffmpeg.zip -DestinationPath .
        $ffmpegPath = Get-ChildItem -Path . -Filter ffmpeg.exe -Recurse | Select-Object -First 1
        if ($ffmpegPath) { Move-Item $ffmpegPath.FullName . } else { Write-Error "ffmpeg.exe not found!" }

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name "AutoClipintisari" --add-binary "ffmpeg.exe;." --add-data "README.md;." AutoClipintisari.py

    - name: List build output
      run: |
        dir dist

    - name: Upload Artifact (Hasil Jadi)
      uses: actions/upload-artifact@v4
      with:
        name: AutoClipintisari-Windows
        path: dist/*
        retention-days: 7
